[build]
    functions = "netlify/functions"
    publish = "public"
    command = "GOOS=linux go build -mod=vendor -o main ./netlify/functions"

[build.environment]
    GO111MODULE = "on"
    NETLIFY_BUILD_DEBUG = "true"